// <auto-generated />
using System;
using LibraryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Россия",
                            FirstName = "Лев",
                            LastName = "Толстой"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Россия",
                            FirstName = "Федор",
                            LastName = "Достоевский"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1860, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Россия",
                            FirstName = "Антон",
                            LastName = "Чехов"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1799, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Россия",
                            FirstName = "Александр",
                            LastName = "Пушкин"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1891, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Country = "Россия",
                            FirstName = "Михаил",
                            LastName = "Булгаков"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 1,
                            ISBN = "978-5-17-123456-7",
                            PublishYear = 1869,
                            QuantityInStock = 10,
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            GenreId = 1,
                            ISBN = "978-5-17-123457-4",
                            PublishYear = 1877,
                            QuantityInStock = 8,
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            GenreId = 1,
                            ISBN = "978-5-17-123458-1",
                            PublishYear = 1866,
                            QuantityInStock = 7,
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            GenreId = 1,
                            ISBN = "978-5-17-123459-8",
                            PublishYear = 1869,
                            QuantityInStock = 5,
                            Title = "Идиот"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            GenreId = 4,
                            ISBN = "978-5-17-123460-4",
                            PublishYear = 1904,
                            QuantityInStock = 6,
                            Title = "Вишневый сад"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            GenreId = 1,
                            ISBN = "978-5-17-123461-1",
                            PublishYear = 1833,
                            QuantityInStock = 9,
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            GenreId = 3,
                            ISBN = "978-5-17-123462-8",
                            PublishYear = 1967,
                            QuantityInStock = 12,
                            Title = "Мастер и Маргарита"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Художественное произведение большого объема",
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Произведение о расследовании преступлений",
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Произведение о вымышленных мирах",
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Стихотворные произведения",
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Описание жизни человека",
                            Name = "Биография"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.HasOne("LibraryManagement.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraryManagement.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
